### ISSUE TITLE
`pod lib lint` linker error when using a pod with a compiled static library

### ISSUE THREAD

**Issue by fcy** [CocoaPods/Core#241]
I have a pod that depends on `Heap`, which is a private source compiled pod, and when I run `pod lib lint` on the pod I get this errors:

>Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Heap", referenced from:
      objc-class-ref in SomeClass.o
ld: symbol(s) not found for architecture x86_64

If I open the Example project that uses my pod things build normally. This started happening on `0.37.1`, used to work with `0.36.4`.

### Steps to Reproduce

1. Create a new pod: `pod lib create test`
2. Edit `test.podspec` to include a dependency `Heap, '~> 2'`
3. Create a class, import Heap, and use some method like `[Heap track:@"something"]`
4. Update and build the Example project, things build just fine
5.Run `pod lib lint --verbose` and there will be a linker error complaining about missing Heap

Or, download this [sample project](https://dl.dropboxusercontent.com/u/2702446/pod-lib-lint-test.zip).

---

Let me know you need more information.

**Comment by fcy** [comment]
This still happens on `0.37.2`.

**Comment by segiddins** [comment]
Does it happen if you run `pod lib lint --use-libraries`?

**Comment by fcy** [comment]
It works with `--use-libraries`, did it used to be the default? Any implications of that change that we should be aware of?

**Comment by segiddins** [comment]
Yes, it used to lint with libraries by default, but now it lints as a framework.
